
import { Inter } from "next/font/google";
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import 'primereact/resources/primereact.css';
import 'primereact/resources/themes/lara-light-purple/theme.css';
import { Menubar } from 'primereact/menubar';
import { Card } from 'primereact/card';
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const items = [
    {
      label: 'Home',
      icon: 'pi pi-home',
      url: '/'
    },
    {
      label: 'Users',
      icon: 'pi pi-user',
      items: [
        {
          label: 'Users List',
          icon: 'pi pi-user',
          url: '/users' // Replace '/profile' with your actual user profile page URL
        },
      ]
    },
    {
      label: 'Contact',
      icon: 'pi pi-envelope'
    }
  ];

  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" />
      <title>Next App</title>
      <meta charSet="utf-8" />
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <meta name="description" content="Web site created using create-next-app" />
      <body className={inter.className}>
        <div className='layout-wrapper'>
          <Card role="region">
            <Menubar model={items} />
          </Card>
          <div className="layout-main-container py-4 px-4 mx-0 md:mx-6 lg:mx-8 lg:px-8 relative lg:static">
            <Card role="region">
              {children}
            </Card>
          </div>
        </div>
      </body>
    </html>
  );
}
